### ISSUE TITLE
Add our Paper

### ISSUE THREAD

**Issue by SeucheAchat9115** [wangs311/awesome-domain-adaptation-object-detection#5]
Hi,

first, thank you for your awesome repo. 
I would recommend to add out recent arxiv paper "AWADA: Attention-Weighted Adversarial Domain Adaptation for Object Detection" at https://arxiv.org/abs/2208.14662. I think this would nicely fit to this.

Thanks in advance.

**Comment by wangs311** [comment]
Hi, I have added this paper. Thanks for your recommendation.
